### ISSUE TITLE
Store User Device Connectivity Information

### ISSUE THREAD

**Issue by AO-StreetArt** [AO-StreetArt/CrazyIvan#56]
Store User Device Connectivity Information during Device Registration.  This will be used for UDP Communications.

**Comment by AO-StreetArt** [comment]
This should also involve supporting messages with only a user device as the base object, and not a scene.
Allow us to perform CRUD operations on UD's separately from Scenes.

**Comment by AO-StreetArt** [comment]
Would be a much simpler change to allow a SceneList message where the scene is empty except for a User Device.

A little less clear in terms of API but will require significantly less changes.

Message type 7 is device create, 8 is device retrieve, 9 is device update, 10 is device delete.

We will want to store a list of connection objects, each containing a connection string, connection type, and hostname and port fields.

**Comment by AO-StreetArt** [comment]
* Addition of new message types
* Additions to Message Processor
* Updates to message processor, registration message can create new user device or use existing record.  Currently only creates new

**Comment by AO-StreetArt** [comment]
We only need to add device retrieve.

Devices are created/updated on registration, deleted sometime after last de-registration (not implemented yet).

**Comment by swolfand** [comment]
Why are you storing connectivity information? seems like the connection is likely to change. wouldn't it be safer to always assume connection is bad and go from there?

**Comment by AO-StreetArt** [comment]
It's to support the UDP network.  This handles high-performance traffic (particularly transformations of objects in space).  The devices need to tell me what address to broadcast this information to, particularly because it is a fire-and-forget architecture.  This information is constantly streaming to all registered devices.

The HTTP Network handles the majority of other communications (scene creation, registration, large file transfers, etc).  Here, we don't care about the device connectivity information, as we're only responding to each request as it comes in.

Does this make sense?  I eventually also want to potentially support allowing the devices to communicate directly with each other where possible.  I see both cases as needing to store some connectivity information on the device.

**Comment by swolfand** [comment]
Nope! but if it makes sense to you then works for me lol. My knowledge is limited

**Comment by swolfand** [comment]
(Didn't mean for that to sound rude. I just truly don't know the architecture enough to get it without looking into it a bit further but I trust you)

**Comment by AO-StreetArt** [comment]
No not at all, alot of that design has yet to even be documented, it's still floating around in my head as theories.  None of it is implemented yet.

**Comment by AO-StreetArt** [comment]
Basically I think about it like this: 
 A video game needs two kinds of messaging.  First, it needs some reliable but potentially slower method to communicate big game assets (like the level), as well as to let the client login and find a game and such.  This can be HTTP, slower but it's request-response so we have a guarantee of recieving the message.

It also needs some super-fast messaging for communicating to everyone once we start actually playing.  For this, we are willing to sacrifice some of the promises of HTTP in return for some additional speed.  Therefore, we use UDP to handle that.  The thing is, with UDP, it's not really the client connecting to the server.  It's the server connecting to the client.  It's just broadcasting information without expecting any sort of response, so it needs to know where to send the message.

**Comment by AO-StreetArt** [comment]
The same principles apply here, whether the client is playing a game or doing something else.

**Comment by swolfand** [comment]
ah makes sense. so connectivity information isn't strength of connection like I was interpreting it.

**Comment by AO-StreetArt** [comment]
No it's literally the hostname and port of the device where we can start broadcasting that information to
